
import axios from 'axios'
import Head from 'next/head'
import Body from '../components/Body'
import Header from '../components/Header'


export default function Index(props) {
 

  return (
    <div className=''>
      <div className='max-w-5xl mx-auto'>
        <Head>
          <title>Blog app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header/>

        <Body content={props.blogdata}/>
      </div>
    </div>
    
  )
}

export async function getStaticProps(context) {
  const response = await axios.get('http://localhost:5000')
  return {
    props: {
      blogdata : response.data
    }, 
    
  }
}
